// scripts/generate-remote-docs.ts
/* eslint-disable no-console */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { REMOTE_SOURCES, type RemoteRepo } from "./remoteSources";

type TreeEntry = { path: string; type: "blob" | "tree" };
type RepoInfo = { private?: boolean; default_branch?: string };

const OUT_FILE = resolve(__dirname, ".generated/remoteDocs.ts");

function parseGitHubRepo(url: string): { owner: string; repo: string } {
  const normalized = url.replace(/^git\+/, "").replace(/\.git(?:[#?].*)?$/, "");
  const u = new URL(normalized);
  const parts = u.pathname.split("/").filter(Boolean);
  const owner = parts[0];
  const repo = parts[1];
  if (!owner || !repo)
    throw new Error(`Cannot parse owner/repo from URL: ${url}`);
  return { owner, repo };
}

async function fetchJson<T>(
  url: string
): Promise<{ ok: boolean; status: number; json?: T }> {
  const res = await fetch(url, {
    headers: {
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });
  if (!res.ok) return { ok: false, status: res.status };
  return { ok: true, status: res.status, json: (await res.json()) as T };
}

async function buildFromRepo(spec: RemoteRepo) {
  const { owner, repo } = parseGitHubRepo(spec.repoUrl);

  const repoInfoResp = await fetchJson<RepoInfo>(
    `https://api.github.com/repos/${owner}/${repo}`
  );
  if (!repoInfoResp.ok) {
    console.warn(`[skip] ${owner}/${repo}: HTTP ${repoInfoResp.status}`);
    return null;
  }
  const info = repoInfoResp.json!;
  if (info.private) {
    console.warn(`[skip] ${owner}/${repo}: private (no auth)`);
    return null;
  }

  const branch = spec.branch || info.default_branch || "master";

  const treeResp = await fetchJson<{ tree?: TreeEntry[]; truncated?: boolean }>(
    `https://api.github.com/repos/${owner}/${repo}/git/trees/${encodeURIComponent(
      branch
    )}?recursive=1`
  );
  if (!treeResp.ok || !treeResp.json?.tree) {
    console.warn(
      `[skip] ${owner}/${repo}@${branch}: cannot read tree (HTTP ${treeResp.status})`
    );
    return null;
  }

  const exts = (
    spec.includeExtensions?.length ? spec.includeExtensions : [".md", ".mdx"]
  ).map((e) => e.toLowerCase());
  const withinPrefixes = (p: string) =>
    !spec.pathPrefixFilter?.length ||
    spec.pathPrefixFilter.some((prefix) => p.startsWith(prefix));

  const documents = treeResp.json.tree
    .filter((n) => n.type === "blob")
    .map((n) => n.path)
    .filter(
      (p) =>
        exts.some((ext) => p.toLowerCase().endsWith(ext)) && withinPrefixes(p)
    )
    .sort();

  if (treeResp.json.truncated) {
    console.warn(
      `[warn] ${owner}/${repo}@${branch}: GitHub truncated tree; some files may be missing`
    );
  }

  const sourceBaseUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/`;

  const pluginEntry: [string, any] = [
    "docusaurus-plugin-remote-content",
    {
      name: spec.name,
      sourceBaseUrl,
      outDir: spec.outDir,
      documents,
    },
  ];

  const fixEntry = {
    name: spec.name,
    gitUrl: spec.repoUrl,
    branch,
    outDir: spec.outDir,
    sourceBaseUrl,
    documents,
  };

  return { pluginEntry, fixEntry };
}

async function run() {
  const dir = dirname(OUT_FILE);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const pluginEntries: Array<[string, any]> = [];
  const fixEntries: any[] = [];

  for (const spec of REMOTE_SOURCES) {
    try {
      const built = await buildFromRepo(spec);
      if (built) {
        pluginEntries.push(built.pluginEntry);
        fixEntries.push(built.fixEntry);
        console.log(
          `[ok] ${spec.name}: ${built.pluginEntry[1].documents.length} docs -> ${spec.outDir}`
        );
      }
    } catch (err: any) {
      console.warn(`[skip] ${spec.repoUrl}: ${err?.message || err}`);
    }
  }

  const file = `/* AUTO-GENERATED by scripts/generate-remote-docs.ts */
export type RemotePluginEntry = [string, any];
export const remotePlugins: RemotePluginEntry[] = ${JSON.stringify(
    pluginEntries,
    null,
    2
  )};

export type RemoteFixEntry = {
  name: string;
  gitUrl: string;
  branch: string;
  outDir: string;
  sourceBaseUrl: string;
  documents: string[];
};
export type RemoteFixMap = RemoteFixEntry[];
export const remoteFixMap: RemoteFixMap = ${JSON.stringify(
    fixEntries,
    null,
    2
  )};
`;
  writeFileSync(OUT_FILE, file, "utf8");
  console.log(`Wrote ${OUT_FILE}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
