/* AUTO-GENERATED by scripts/generate-remote-docs.ts */
export type RemotePluginEntry = [string, any];
export const remotePlugins: RemotePluginEntry[] = [];

export type RemoteFixEntry = {
  name: string;
  gitUrl: string;
  branch: string;
  outDir: string;
  sourceBaseUrl: string;
  documents: string[];
};
export type RemoteFixMap = RemoteFixEntry[];
export const remoteFixMap: RemoteFixMap = [];
